#!/usr/bin/env bash
# send_alert.sh — Email and Slack alert dispatcher with cooldown
# Defines send_alert(type, detail, severity, hostname); sourced by health_monitor.sh.
# Cooldown prevents duplicate alerts within ALERT_COOLDOWN seconds.
set -euo pipefail

send_alert() {
    local alert_type="${1:-UNKNOWN}"
    local alert_detail="${2:-No details provided}"
    local severity="${3:-WARNING}"    # WARNING | CRITICAL
    local server_name="${4:-$(hostname -s 2>/dev/null || echo unknown)}"

    if [[ -z "${ALERT_METHOD:-}" ]]; then
        local _cfg
        _cfg="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)/config.conf"
        [[ -f "$_cfg" ]] || return 1
        # shellcheck source=../config.conf
        source "$_cfg"
    fi

    # ── Cooldown check ────────────────────────────────────────────────────────
    # One cooldown file per alert type; skip if sent within ALERT_COOLDOWN seconds
    local cooldown_file="${COOLDOWN_DIR:-/var/log/healthmonitor/.cooldown}/${alert_type}.last"
    mkdir -p "$(dirname "$cooldown_file")"
    local now cooldown_secs last_sent
    now=$(date +%s)
    cooldown_secs="${ALERT_COOLDOWN:-1800}"
    if [[ -f "$cooldown_file" ]]; then
        last_sent=$(cat "$cooldown_file")
        if (( now - last_sent < cooldown_secs )); then
            return 0  # Still within cooldown window; suppress duplicate
        fi
    fi
    echo "$now" > "$cooldown_file"

    # ── Compose alert message ─────────────────────────────────────────────────
    local ts subject body uptime_str
    ts=$(date '+%Y-%m-%d %H:%M:%S')
    uptime_str=$(uptime -p 2>/dev/null || uptime | awk -F'up ' '{print $2}' | cut -d',' -f1)
    subject="${REPORT_SUBJECT_PREFIX:-[ServerMon]} ${severity} — ${server_name} — ${alert_type}"

    # Plain-text body (also used as Slack fallback)
    body="$(cat <<EOF
SERVER ALERT — ${severity}
════════════════════════════
Server:      ${server_name}
Time:        ${ts}
Alert Type:  ${alert_type}
Severity:    ${severity}
Detail:      ${alert_detail}

Server Uptime: ${uptime_str}
Log:           ${LOG_FILE:-/var/log/healthmonitor/monitor.log}

-- Auto-generated by ServerHealthMonitor v${VERSION:-1.0.0}
EOF
)"

    # ── Dispatch via configured channel(s) ───────────────────────────────────
    local method="${ALERT_METHOD:-email}"

    _send_email() {
        local recipient="${ALERT_EMAIL:-root}"
        if command -v mailx &>/dev/null; then
            echo "$body" | mailx -s "$subject" "$recipient" 2>/dev/null && return 0
        fi
        if command -v sendmail &>/dev/null; then
            { echo "Subject: ${subject}"; echo "To: ${recipient}"; echo ""; echo "$body"; } | \
                sendmail "$recipient" 2>/dev/null && return 0
        fi
        echo "[WARN] No mail agent found (install mailx/sendmail). Alert NOT emailed." >&2
        return 1
    }

    _send_slack() {
        local webhook="${SLACK_WEBHOOK:-}"
        [[ -z "$webhook" || "$webhook" == "https://hooks.slack.com/services/YOUR/WEBHOOK/URL" ]] && {
            echo "[WARN] Slack webhook not configured. Alert NOT sent to Slack." >&2
            return 1
        }
        local emoji=":warning:"
        [[ "$severity" == "CRITICAL" ]] && emoji=":rotating_light:"
        local payload
        payload=$(printf '{"text":"%s *%s* — %s\n%s\nServer: `%s` | Time: `%s`"}' \
                  "$emoji" "$severity" "$alert_type" "$alert_detail" "$server_name" "$ts")
        curl -fsS -X POST -H 'Content-type: application/json' \
             --data "$payload" "$webhook" &>/dev/null
    }

    case "$method" in
        email) _send_email ;;
        slack) _send_slack ;;
        both)  _send_email; _send_slack ;;
        *)     echo "[WARN] Unknown ALERT_METHOD '${method}'. Defaulting to email." >&2; _send_email ;;
    esac

    return 0
}
