#!/usr/bin/env bash
# install.sh — One-command setup for Server Health Monitor v1.0.0
# Installs scripts, sets up cron jobs, creates log directories.
# Usage: sudo bash install.sh [--uninstall]
set -euo pipefail
trap 'echo -e "\n[ERROR] Installation failed at line ${LINENO}. Run: journalctl -xe for details." >&2; exit 1' ERR

# ── Colours ───────────────────────────────────────────────────────────────────
RED='\033[0;31m'; GREEN='\033[0;32m'; YELLOW='\033[1;33m'
CYAN='\033[0;36m'; BOLD='\033[1m'; RESET='\033[0m'

log()  { echo -e "${CYAN}[$(date '+%H:%M:%S')] INFO${RESET}  $*"; }
ok()   { echo -e "${GREEN}[$(date '+%H:%M:%S')]  OK  ${RESET}  $*"; }
warn() { echo -e "${YELLOW}[$(date '+%H:%M:%S')] WARN${RESET}  $*"; }
die()  { echo -e "${RED}[$(date '+%H:%M:%S')] FAIL${RESET}  $*" >&2; exit 1; }
step() { echo -e "\n${BOLD}${CYAN}══ $* ══${RESET}"; }

# ── Paths ─────────────────────────────────────────────────────────────────────
INSTALL_DIR="/usr/local/bin/healthmonitor"
CONFIG_DIR="/etc/healthmonitor"
LOG_DIR="/var/log/healthmonitor"
SRC_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

# ── Root check ────────────────────────────────────────────────────────────────
[[ $EUID -eq 0 ]] || die "Must be run as root: sudo bash install.sh"

# ── Uninstall mode ────────────────────────────────────────────────────────────
if [[ "${1:-}" == "--uninstall" ]]; then
    step "UNINSTALLING Server Health Monitor"
    crontab -l 2>/dev/null | grep -v healthmonitor | crontab - && ok "Cron jobs removed"
    rm -rf "$INSTALL_DIR" && ok "Scripts removed: ${INSTALL_DIR}"
    rm -rf "$CONFIG_DIR"  && ok "Config removed:  ${CONFIG_DIR}"
    warn "Logs preserved at ${LOG_DIR}. Remove manually with: rm -rf ${LOG_DIR}"
    echo -e "\n${GREEN}${BOLD}Uninstall complete.${RESET}"
    exit 0
fi

# ── Banner ────────────────────────────────────────────────────────────────────
echo -e "${BOLD}"
cat <<'BANNER'
╔═══════════════════════════════════════════════════════╗
║     Server Health Monitor  —  Installer  v1.0.0       ║
║     RHEL 9 / Rocky Linux / CentOS / Ubuntu            ║
╚═══════════════════════════════════════════════════════╝
BANNER
echo -e "${RESET}"

# ── Dependency check ──────────────────────────────────────────────────────────
step "Checking dependencies"
MISSING=()
for cmd in top free df ping systemctl awk curl; do
    if command -v "$cmd" &>/dev/null; then
        ok "Found: $cmd"
    else
        warn "Missing: $cmd"
        MISSING+=("$cmd")
    fi
done
command -v mailx &>/dev/null && ok "Found: mailx (email alerts enabled)" || \
    warn "mailx not found — email alerts disabled. Install: dnf install mailx"
[[ ${#MISSING[@]} -gt 0 ]] && die "Required commands missing: ${MISSING[*]}"

# ── Create directories ────────────────────────────────────────────────────────
step "Creating directories"
for dir in "$INSTALL_DIR" "$INSTALL_DIR/modules" "$INSTALL_DIR/reports" \
           "$CONFIG_DIR" "$LOG_DIR" "${LOG_DIR}/.cooldown" "${LOG_DIR}/reports"; do
    mkdir -p "$dir"
    ok "Created: $dir"
done

# ── Install config ────────────────────────────────────────────────────────────
step "Installing configuration"
if [[ -f "${CONFIG_DIR}/config.conf" ]]; then
    warn "Existing config found at ${CONFIG_DIR}/config.conf — backing up"
    cp "${CONFIG_DIR}/config.conf" "${CONFIG_DIR}/config.conf.bak.$(date +%s)"
fi
cp "${SRC_DIR}/config.conf" "${CONFIG_DIR}/config.conf"
chmod 640 "${CONFIG_DIR}/config.conf"
ok "Config installed: ${CONFIG_DIR}/config.conf"

# Create symlink so scripts can find config at expected path
ln -sf "${CONFIG_DIR}/config.conf" "${INSTALL_DIR}/config.conf"

# ── Install scripts ───────────────────────────────────────────────────────────
step "Installing scripts"
cp "${SRC_DIR}/health_monitor.sh" "${INSTALL_DIR}/"
for mod in check_cpu check_ram check_disk check_services check_network send_alert; do
    cp "${SRC_DIR}/modules/${mod}.sh" "${INSTALL_DIR}/modules/"
done
cp "${SRC_DIR}/reports/generate_report.sh" "${INSTALL_DIR}/reports/"

# Make all scripts executable
find "$INSTALL_DIR" -name "*.sh" -exec chmod 755 {} \;
ok "All scripts installed and made executable"

# ── Set up cron jobs ──────────────────────────────────────────────────────────
step "Setting up cron jobs"
CRON_MONITOR="*/5 * * * * root ${INSTALL_DIR}/health_monitor.sh >> ${LOG_DIR}/cron.log 2>&1"
CRON_REPORT="0 8 * * * root ${INSTALL_DIR}/reports/generate_report.sh >> ${LOG_DIR}/cron.log 2>&1"
CRON_FILE="/etc/cron.d/healthmonitor"
cat > "$CRON_FILE" <<CRONTAB
# Server Health Monitor — auto-generated by install.sh
SHELL=/bin/bash
PATH=/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin

${CRON_MONITOR}
${CRON_REPORT}
CRONTAB
chmod 644 "$CRON_FILE"
ok "Cron installed: ${CRON_FILE}"
ok "  Monitor: every 5 minutes"
ok "  Report:  daily at 08:00"

# ── Test run ──────────────────────────────────────────────────────────────────
step "Running initial health check (dry-run)"
if bash "${INSTALL_DIR}/health_monitor.sh" --dry-run --verbose; then
    ok "Initial health check passed"
else
    warn "Health check returned alerts — this is normal if thresholds are tight"
    warn "Edit ${CONFIG_DIR}/config.conf to tune thresholds"
fi

# ── Final instructions ────────────────────────────────────────────────────────
echo -e "\n${GREEN}${BOLD}╔═══════════════════════════════════════════════════════╗${RESET}"
echo -e "${GREEN}${BOLD}║         Installation complete!                        ║${RESET}"
echo -e "${GREEN}${BOLD}╚═══════════════════════════════════════════════════════╝${RESET}"
cat <<INFO

  Config:   ${CONFIG_DIR}/config.conf
  Scripts:  ${INSTALL_DIR}/
  Logs:     ${LOG_DIR}/monitor.log
  Alerts:   ${LOG_DIR}/alerts.log

  Next steps:
  1. Edit ${CONFIG_DIR}/config.conf to set your email and thresholds
  2. Test alerts: bash ${INSTALL_DIR}/health_monitor.sh --verbose
  3. Check logs:  tail -f ${LOG_DIR}/monitor.log
  4. Uninstall:   sudo bash ${SRC_DIR}/install.sh --uninstall

INFO
